wallet_crypto/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :wallets
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

wallet_crypto/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

wallet_crypto/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one :wallet

        
end

wallet_crypto/app/models/wallet.rb
class Wallet < ApplicationRecord
    belongs_to :user
end

wallet_crypto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

wallet_crypto/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   @bite =rand(1..6) 
   @alpha =0
   return @toto = @alpha + @bite +1
  end
end

wallet_crypto/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

wallet_crypto/app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :set_wallet, only: %i[ show edit update destroy ]

  # GET /wallets or /wallets.json
  def index
    @wallets = Wallet.all
  end

  # GET /wallets/1 or /wallets/1.json
  def show
  end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
  end

  # GET /wallets/1/edit
  def edit
  end

  # POST /wallets or /wallets.json
  def create
    @wallet = Wallet.new(wallet_params)

    respond_to do |format|
      if @wallet.save
        format.html { redirect_to @wallet, notice: "Wallet was successfully created." }
        format.json { render :show, status: :created, location: @wallet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallets/1 or /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to @wallet, notice: "Wallet was successfully updated." }
        format.json { render :show, status: :ok, location: @wallet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1 or /wallets/1.json
  def destroy
    @wallet.destroy
    respond_to do |format|
      format.html { redirect_to wallets_url, notice: "Wallet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = Wallet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wallet_params
      params.require(:wallet).permit(:account)
    end
end

wallet_crypto/app/helpers/application_helper.rb
module ApplicationHelper
end

wallet_crypto/app/helpers/home_helper.rb
module HomeHelper
end

wallet_crypto/app/helpers/users_helper.rb
module UsersHelper
end

wallet_crypto/app/helpers/wallets_helper.rb
module WalletsHelper
end

wallet_crypto/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb <%= @bite %> </p>
<%# <button type="button" class="btn btn-primary actions">Primary</button> %>
<div class="btn btn-primary">
  <%= link_to 'clic',   @index , :class => "btn" %> |
  <%= link_to 'NEW WALLET', new_wallet_path, :class => "btn"%>
</div>

<p><%=@alpha%></p>

<p>account is <%=@toto%></p>

wallet_crypto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WalletCrypto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  </head>

  <body>
    <header> 

  <ul class="nav nav-tabs">

  <li class="nav-item p-3">
    <%= link_to "Home", root_path, :class =>"nav-link" %>
  </li>
  <li class="nav-item p-3">
    <%= link_to "wallet", wallets_path, :class =>"nav-link" %>
    
  </li>
   <li class="nav-item dropdown p-3">
   
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class= "nav-link"> <% if user_signed_in? %>
            <%= link_to "Mon profil", user_path(current_user), :class =>"nav-link" %>
             <%= link_to "Deconexion", destroy_user_session_path, method: :delete, :class =>"nav-link" %>
              <% else %>
             <%= link_to "Connexion", new_user_session_path, :class =>"nav-link" %>
             <%= link_to "Inscription", new_user_registration_path, :class =>"nav-link" %>
               <% end %></li>
            
            
          </ul>
        </li>

    </header> 
  
 <div class="container"> 
      <%= yield %>
 </div> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
  </body>
</html>

wallet_crypto/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

wallet_crypto/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

wallet_crypto/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

wallet_crypto/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

wallet_crypto/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

wallet_crypto/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

wallet_crypto/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

wallet_crypto/app/views/wallets/_form.html.erb
<%= form_with(model: wallet, local: true) do |form| %>
  <% if wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
      <% wallet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% form.hidden_field :user_id, :value => current_user.id %>
  <div class="field">
    <%= form.label :account %>
    <%= form.number_field :account %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

wallet_crypto/app/views/wallets/edit.html.erb
<h1>Editing Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Show', @wallet %> |
<%= link_to 'Back', wallets_path %>

wallet_crypto/app/views/wallets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wallets</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wallets.each do |wallet| %>
      <tr>
        <td><%= wallet.account %></td>
        <td><%= link_to 'Show', wallet %></td>
        <td><%= link_to 'Edit', edit_wallet_path(wallet) %></td>
        <td><%= link_to 'Destroy', wallet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wallet', new_wallet_path %>

wallet_crypto/app/views/wallets/new.html.erb
<h1>New Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Back', wallets_path, :class => "btn btn-primary" %>

wallet_crypto/app/views/wallets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @wallet.account %>
</p>

<%= link_to 'Edit', edit_wallet_path(@wallet) %> |
<%= link_to 'Back', wallets_path %>